name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ] # Triggers automatically when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Ensure the /app directory exists
            mkdir -p /app
            cd /app
            
            # If the repository hasn't been cloned yet, clone it
            if [ ! -d "learn-from-news" ]; then
              git clone https://github.com/liwei9981/learn-from-news.git
            fi
            
            # Navigate to the folder
            cd learn-from-news
            
            # Pull the latest code from GitHub
            git pull origin main
            
            # Rebuild and restart the Docker container
            docker compose up -d --build
